In [1]:
import torch

In [2]:
a = torch.randn(3, 3)
a

tensor([[-0.1057,  0.6488,  1.0935],
        [-0.0345,  0.0539, -0.7260],
        [ 1.8081, -0.6186, -0.0048]])

In [3]:
torch.triu(a)


tensor([[-0.1057,  0.6488,  1.0935],
        [ 0.0000,  0.0539, -0.7260],
        [ 0.0000,  0.0000, -0.0048]])

In [15]:
torch.triu(a, diagonal=1)

tensor([[ 0.0000,  0.6488,  1.0935],
        [ 0.0000,  0.0000, -0.7260],
        [ 0.0000,  0.0000,  0.0000]])

In [5]:
torch.triu(a, diagonal=-1)

tensor([[-0.1057,  0.6488,  1.0935],
        [-0.0345,  0.0539, -0.7260],
        [ 0.0000, -0.6186, -0.0048]])